### ISSUE TITLE
about selead class

### ISSUE THREAD

**Issue by uziasferreirazup** [juanchosaravia/autodsl#10]
```
sealed class Test {
    @AutoDsl
    data class TestOne(val route: Route) : Test()

    @AutoDsl
    data class TestTwo(val route: Route) : Test()
}

```

actual the auto dsl not has support to selead class, there is any plan to add this support?

**Comment by juanchosaravia** [comment]
Hi Uzias! what do you mean by supporting sealed class? right now this code compiles and will generate builders for TestOne and TestTwo. Is there any other feature you are looking for?

**Comment by juanchosaravia** [comment]
Oh my bad, will not compile. I think what you can do for the time being is using it in this way:

```
sealed class Test

@AutoDsl
data class TestOne(val route: Route) : Test()

@AutoDsl
data class TestTwo(val route: Route) : Test()
```

move the data classes outside the sealed class. The disadvantage is that you will not have the context of "Test.TestOne" but in terms of functionality it will work as the other declaration of sealed class
