### ISSUE TITLE
Not nullable property with default value will not work

### ISSUE THREAD

**Issue by alaxwork** [juanchosaravia/autodsl#5]
I tried to extend test Person class:
`
@AutoDsl // indicates to create an associated DSL for this class
class Person(
    val name: String,
    val age: Int,
    val address: Address?,
    val friends: List<Person>?,
    @AutoDslCollection(concreteType = TreeSet::class) // specify concrete type
    val keys: Set<String>?,
    val items: Map<String, String> = emptyMap()
)
`
It doesn't work. Is it a bug?

**Comment by juanchosaravia** [comment]
Default values are not supported, checkout the wiki where it explains a little more about this:
https://github.com/juanchosaravia/autodsl/wiki#default-parameters

**Comment by JanuszHain** [comment]
@juanchosaravia is it possible to create new annotation to support this? 

For example:
@AutoDslDefaultValue(default = "John") val name
