### ISSUE TITLE
Compile-time check for required value

### ISSUE THREAD

**Issue by Globegitter** [juanchosaravia/autodsl#8]
First of all thanks for this library it is really looking great. The only issue I am having is that there is no compile time check if required variables where forgotten to be set. Do you know if it would be possible to get it working this way? There is some talk about this here btw: https://discuss.kotlinlang.org/t/automatically-generating-type-safe-builders-for-data-classes/14/2?u=mpadourek

**Comment by juanchosaravia** [comment]
Thanks for the article! I'll take a look and see what I can do. Of course feel free to send any pull request!

**Comment by juanchosaravia** [comment]
Hi @Globegitter, I just read the entire thread and unfortunately I have to say I agree with Varia comment that it's too complex to provide a feature like this. Despite of this, I'm totally open to any suggestion/approach that I may not be aware of. If that's the case please feel free to share it here. Meanwhile I'm going to be closing this feature request for the time being and thanks again!
